/** @jsx jsx */
import { jsx } from "@emotion/react";

export default function MyComponent(props) {
  return (
    <div
      css={{
        display: "flex",
        maxWidth: "375px",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        height: "812px",
        width: "375px",
        backgroundColor: "rgba(255, 255, 255, 1)",
      }}
    >
      <div
        css={{
          display: "flex",
          maxWidth: "375px",
          boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.11999999731779099)",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "375px",
            height: "50px",
            width: "375px",
            backgroundColor: "rgba(104, 93, 197, 1)",
          }}
        />
        <div
          css={{
            display: "flex",
            maxWidth: "162px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            height: "25px",
            width: "162px",
          }}
        >
          <div
            css={{
              display: "flex",
              flexDirection: "column",
              maxWidth: "153.94525146484375px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "153.94525146484375px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "10.181563377380371px",
                  width: "10.181563377380371px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F204a9b0fc8bf40f4b685d5fba6234aec"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "133.03903853667003%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "11.855867385864258px",
                  width: "11.855867385864258px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F368115aab311450ba00db8fe1450ac8d"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "114.25105885899829%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "10.045812606811523px",
                  width: "10.045812606811523px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F81070b80c8064139aa17eefdebcf20d1"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "134.83681764165215%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "10.000553131103516px",
                  width: "10.000553131103516px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff2943f0304e9477e8a086dac98bcbb79"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "135.44704825515862%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "10.588821411132812px",
                  width: "10.588821411132812px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F796a382aea7241aa8ed9d37bfd69076a"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "133.07341389641024%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "10.226821899414062px",
                  width: "10.226821899414062px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb93523456234052a108a8e3491f735b"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "135.11705024432095%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "10.045814514160156px",
                  width: "10.045814514160156px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc9a6da8a98bc4e40b6f1acb32d665c08"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "134.83679204085894%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "58.55531311035156px",
                  width: "58.55531311035156px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff954ef049c8e41d2953c6d62d1980680"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "24.219525451722106%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "1.1765289306640625px",
                  width: "1.1765289306640625px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd672c6e6ce874fd38b4d971f7454fcfe"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "100.44971143246222%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
            </div>
          </div>
        </div>
        <div
          css={{
            maxWidth: "137px",
            color: "rgba(255, 255, 255, 1)",
            fontSize: "11px",
            letterSpacing: "0%",
            textAlign: "left",
            fontFamily: "Mandali, sans-serif",
          }}
        >
          /INTERACTION Design
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "0px",
          }}
        />
      </div>
      <div
        css={{
          display: "flex",
          flexDirection: "column",
          maxWidth: "35px",
        }}
      >
        <div
          css={{
            display: "flex",
            position: "relative",
            minWidth: "20px",
            minHeight: "20px",
            maxWidth: "35px",
            width: "35px",
          }}
        >
          <picture>
            <source
              srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2"
              type="image/webp"
            />

            <img
              src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2"
              srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3592a395f2d64e99be162fe53bfb8bc2"
              css={{
                objectFit: "cover",
                objectPosition: "center",
                position: "absolute",
                height: "100%",
                width: "100%",
                top: "0",
                left: "0",
              }}
            />
          </picture>

          <div
            className="builder-image-sizer"
            css={{
              width: "100%",
              paddingTop: "85.71428571428571%",
              pointerEvents: "none",
              fontSize: "0",
            }}
          />
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "335px",
        }}
      >
        <div
          css={{
            display: "flex",
            flexDirection: "column",
            maxWidth: "335px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "335px",
              height: "215px",
              width: "335px",
              borderRadius: "4px",
              borderColor: "rgba(218, 218, 218, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "288px",
          }}
        >
          <div
            css={{
              maxWidth: "288px",
              color: "rgba(83, 83, 83, 1)",
              fontSize: "16px",
              lineHeight: "24px",
              letterSpacing: "-0.1599999964237213px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            You’ll be guaranteed a 1 year contract with SCG upon graduation.{" "}
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "168px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "54px",
              width: "168px",
            }}
          >
            <div
              css={{
                maxWidth: "178.63290405273438px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "24px",
                lineHeight: "24px",
                letterSpacing: "-0.2181818187236786px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              1 Year Full-Time
            </div>
            <div
              css={{
                maxWidth: "157.36709594726562px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "16px",
                lineHeight: "22px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              A Full-Time Contract
            </div>
          </div>
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "27.81617546081543px",
              width: "27.81617546081543px",
              borderColor: "rgba(218, 218, 218, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3f721ded0f804a528e30020fd3da247b"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "3.5950305296596126%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "335px",
        }}
      >
        <div
          css={{
            display: "flex",
            flexDirection: "column",
            maxWidth: "335px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "335px",
              height: "287px",
              width: "335px",
              borderRadius: "4px",
              borderColor: "rgba(218, 218, 218, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "288px",
          }}
        >
          <div
            css={{
              maxWidth: "288px",
              color: "rgba(83, 83, 83, 1)",
              fontSize: "16px",
              lineHeight: "24px",
              letterSpacing: "-0.1599999964237213px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Immerse yourself in the professional world during your
            apprenticeship. You’ll learn the ropes from the best and get to
            apply your newly acquired knowledge in the field from day one.{" "}
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "204px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "54px",
              width: "204px",
            }}
          >
            <div
              css={{
                maxWidth: "137px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "24px",
                lineHeight: "24px",
                letterSpacing: "-0.2181818187236786px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              4 hours / day
            </div>
            <div
              css={{
                maxWidth: "204px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "16px",
                lineHeight: "22px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Apprenticeship Commitment
            </div>
          </div>
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "27.81617546081543px",
              width: "27.81617546081543px",
              borderColor: "rgba(218, 218, 218, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9a3f4c2c7cf1466d827a9ca361ad026f"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "3.5950305296596126%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "334px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "24px",
          width: "334px",
        }}
      >
        <div
          css={{
            display: "flex",
            position: "relative",
            minWidth: "20px",
            minHeight: "20px",
            maxWidth: "86.70207214355469px",
            width: "86.70207214355469px",
            borderColor: "rgba(218, 218, 218, 1)",
            borderWidth: "1px",
            borderStyle: "solid",
          }}
        >
          <picture>
            <source
              srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56"
              type="image/webp"
            />

            <img
              src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56"
              srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0a74825183a43c89c6b534d74c93e56"
              css={{
                objectFit: "contain",
                objectPosition: "center",
                position: "absolute",
                height: "100%",
                width: "100%",
                top: "0",
                left: "0",
              }}
            />
          </picture>

          <div
            className="builder-image-sizer"
            css={{
              width: "100%",
              paddingTop: "2.3067499432868828%",
              pointerEvents: "none",
              fontSize: "0",
            }}
          />
        </div>
        <div
          css={{
            maxWidth: "98px",
            color: "rgba(83, 83, 83, 1)",
            fontSize: "16px",
            lineHeight: "24px",
            letterSpacing: "-0.145454540848732px",
            textAlign: "center",
            fontFamily: "Mandali, sans-serif",
          }}
        >
          GRADUATION
        </div>
        <div
          css={{
            display: "flex",
            position: "relative",
            minWidth: "20px",
            minHeight: "20px",
            maxWidth: "86.70206451416016px",
            width: "86.70206451416016px",
            borderColor: "rgba(218, 218, 218, 1)",
            borderWidth: "1px",
            borderStyle: "solid",
          }}
        >
          <picture>
            <source
              srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010"
              type="image/webp"
            />

            <img
              src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010"
              srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7e72cfcff05a4296abceb7a63c464010"
              css={{
                objectFit: "contain",
                objectPosition: "center",
                position: "absolute",
                height: "100%",
                width: "100%",
                top: "0",
                left: "0",
              }}
            />
          </picture>

          <div
            className="builder-image-sizer"
            css={{
              width: "100%",
              paddingTop: "2.3067501462705775%",
              pointerEvents: "none",
              fontSize: "0",
            }}
          />
        </div>
      </div>
    </div>
  );
}
