/** @jsx jsx */
import { jsx } from "@emotion/react";

export default function MyComponent(props) {
  return (
    <>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "411px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc6bb78d74e5b428f9d0c11328b8c897d"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "217px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "22px",
              letterSpacing: "-0.1599999964237213px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            APPRENTICESHIP COMMITMENT
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F533b45a1de384f758a95e6713d1684ce"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "55px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "center",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              TWEETS
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa488452f829d4fdfbe5bbf8dc6e5578e"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "28px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              FSQ
            </div>
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            height: "235px",
            width: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5475599d03e5402c8351a9a892058b65"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "83px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              HOME PAGE
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "238px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0e5f6272c34b402196b779e86ead9e62"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "121px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "40px",
                letterSpacing: "-0.4375px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              PARTICIPATE NOW
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b5b59d2bea84977a5c3dcd74f0f87ed"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "193px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "40px",
                  letterSpacing: "-0.4375px",
                  textAlign: "center",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                {" "}
                ABOUT THE APPRENTICESHIP
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa968f82948d14bbf973f9d44435e037b"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "147px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "22px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                STUDY COMMITMENT
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "375px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "812px",
          width: "375px",
          backgroundColor: "rgba(255, 255, 255, 1)",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "375px",
            boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.11999999731779099)",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "375px",
              height: "50px",
              width: "375px",
              backgroundColor: "rgba(104, 93, 197, 1)",
            }}
          />
          <div
            css={{
              display: "flex",
              maxWidth: "162px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "25px",
              width: "162px",
            }}
          >
            <div
              css={{
                display: "flex",
                flexDirection: "column",
                maxWidth: "153.94525146484375px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "153.94525146484375px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.181563377380371px",
                    width: "10.181563377380371px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8f9c968c1b5418996a2d89ddce1d423"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "133.03903853667003%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "11.855867385864258px",
                    width: "11.855867385864258px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86e0c2df1e9c4257a5412366ea15bb48"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "114.25105885899829%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.045812606811523px",
                    width: "10.045812606811523px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd334337ee938443d81f0866be8f3ee0b"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "134.83681764165215%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.000553131103516px",
                    width: "10.000553131103516px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ec170882a094cfd854cbcf6eebf22ec"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "135.44704825515862%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.588821411132812px",
                    width: "10.588821411132812px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5943b0054b324bbfbfe44d935fc9d11c"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "133.07341389641024%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.226821899414062px",
                    width: "10.226821899414062px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feaf5016d0d5c475aa102493a1f6a2b43"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "135.11705024432095%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.045814514160156px",
                    width: "10.045814514160156px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe9e35b7fa4ef4daf920fd8b09b4ec243"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "134.83679204085894%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "58.55531311035156px",
                    width: "58.55531311035156px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4e2562a4bb394129b16412944c49bb5f"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "24.219525451722106%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "1.1765289306640625px",
                    width: "1.1765289306640625px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb9cf4cb96c0d425db39718c7b38d8d5f"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "100.44971143246222%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
          <div
            css={{
              maxWidth: "137px",
              color: "rgba(255, 255, 255, 1)",
              fontSize: "11px",
              letterSpacing: "0%",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            /INTERACTION Design
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "0px",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            flexDirection: "column",
            maxWidth: "35px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "35px",
              width: "35px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F30dfbd35cdc2428db1d922c064c3b5c4"
                css={{
                  objectFit: "cover",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "85.71428571428571%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "335px",
          }}
        >
          <div
            css={{
              display: "flex",
              flexDirection: "column",
              maxWidth: "335px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "335px",
                height: "215px",
                width: "335px",
                borderRadius: "4px",
                borderColor: "rgba(218, 218, 218, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "288px",
            }}
          >
            <div
              css={{
                maxWidth: "288px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "16px",
                lineHeight: "24px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              You’ll be guaranteed a 1 year contract with SCG upon graduation.{" "}
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "168px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                height: "54px",
                width: "168px",
              }}
            >
              <div
                css={{
                  maxWidth: "178.63290405273438px",
                  color: "rgba(83, 83, 83, 1)",
                  fontSize: "24px",
                  lineHeight: "24px",
                  letterSpacing: "-0.2181818187236786px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                1 Year Full-Time
              </div>
              <div
                css={{
                  maxWidth: "157.36709594726562px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "16px",
                  lineHeight: "22px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                A Full-Time Contract
              </div>
            </div>
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "27.81617546081543px",
                width: "27.81617546081543px",
                borderColor: "rgba(218, 218, 218, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F180a3c84d9d046aba19e96004fa8ae45"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "3.5950305296596126%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "335px",
          }}
        >
          <div
            css={{
              display: "flex",
              flexDirection: "column",
              maxWidth: "335px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "335px",
                height: "287px",
                width: "335px",
                borderRadius: "4px",
                borderColor: "rgba(218, 218, 218, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "288px",
            }}
          >
            <div
              css={{
                maxWidth: "288px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "16px",
                lineHeight: "24px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Immerse yourself in the professional world during your
              apprenticeship. You’ll learn the ropes from the best and get to
              apply your newly acquired knowledge in the field from day one.{" "}
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "204px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                height: "54px",
                width: "204px",
              }}
            >
              <div
                css={{
                  maxWidth: "137px",
                  color: "rgba(83, 83, 83, 1)",
                  fontSize: "24px",
                  lineHeight: "24px",
                  letterSpacing: "-0.2181818187236786px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                4 hours / day
              </div>
              <div
                css={{
                  maxWidth: "204px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "16px",
                  lineHeight: "22px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                Apprenticeship Commitment
              </div>
            </div>
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "27.81617546081543px",
                width: "27.81617546081543px",
                borderColor: "rgba(218, 218, 218, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F28adde5d772249a09882ddcfa02f314d"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "3.5950305296596126%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "334px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            height: "24px",
            width: "334px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "86.70207214355469px",
              width: "86.70207214355469px",
              borderColor: "rgba(218, 218, 218, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe72816ab647a4b61b4971df4159d254b"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "2.3067499432868828%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              maxWidth: "98px",
              color: "rgba(83, 83, 83, 1)",
              fontSize: "16px",
              lineHeight: "24px",
              letterSpacing: "-0.145454540848732px",
              textAlign: "center",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            GRADUATION
          </div>
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "86.70206451416016px",
              width: "86.70206451416016px",
              borderColor: "rgba(218, 218, 218, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe859e20737ed4a8ead1502f1d9f0103e"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "2.3067501462705775%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "411px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a0602354783484682a50f4da1247c50"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "217px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "22px",
              letterSpacing: "-0.1599999964237213px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            APPRENTICESHIP COMMITMENT
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd265355ddaa343d4824ef034bc7d5c3a"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "55px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "center",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              TWEETS
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06f40a76616746beb2d00f9811a806fc"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "28px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              FSQ
            </div>
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            height: "235px",
            width: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F150e8950b9ea46a0a16b27269990ee44"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "83px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              HOME PAGE
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "238px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde7509dcbf2e48b2a09723bc56569a7d"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "121px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "40px",
                letterSpacing: "-0.4375px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              PARTICIPATE NOW
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9445136d36c7450186c1ed1797643c22"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "193px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "40px",
                  letterSpacing: "-0.4375px",
                  textAlign: "center",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                {" "}
                ABOUT THE APPRENTICESHIP
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d33bd9eb0a14c779a22f47c733cfcf6"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "147px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "22px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                STUDY COMMITMENT
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
