/** @jsx jsx */
import { jsx } from "@emotion/react";

export default function MyComponent(props) {
  return (
    <div
      css={{
        display: "flex",
        maxWidth: "238px",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        height: "411px",
        width: "238px",
      }}
    >
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            position: "relative",
            minWidth: "20px",
            minHeight: "20px",
            maxWidth: "195px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            width: "195px",
          }}
        >
          <picture>
            <source
              srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02"
              type="image/webp"
            />

            <img
              src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02"
              srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bf5272b709043c19ebfea477d0e1e02"
              css={{
                objectFit: "contain",
                objectPosition: "center",
                position: "absolute",
                height: "100%",
                width: "100%",
                top: "0",
                left: "0",
              }}
            />
          </picture>

          <div
            className="builder-image-sizer"
            css={{
              width: "100%",
              paddingTop: "15.384615384615385%",
              pointerEvents: "none",
              fontSize: "0",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
            height: "58px",
            width: "235px",
            borderRadius: "29px",
            borderColor: "rgba(230, 230, 230, 1)",
            borderWidth: "1px",
            borderStyle: "solid",
            backgroundColor: "rgba(255, 255, 255, 1)",
          }}
        />
        <div
          css={{
            maxWidth: "217px",
            color: "rgba(104, 93, 197, 1)",
            fontSize: "14px",
            lineHeight: "22px",
            letterSpacing: "-0.1599999964237213px",
            textAlign: "left",
            fontFamily: "Mandali, sans-serif",
          }}
        >
          APPRENTICESHIP COMMITMENT
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F34185962c1bf424aa29c6497e9e4651d"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "55px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "center",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            TWEETS
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6e3c3b7c96ac4c8480c64db3c15ee56c"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "28px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            FSQ
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "235px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F82a6e690909d4a6da797daf1476c5c84"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "83px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            HOME PAGE
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F88f50f6a85864c92a9193c882dccf518"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "121px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "40px",
              letterSpacing: "-0.4375px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            PARTICIPATE NOW
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc196b98194e242438430389f2cdac9cc"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "193px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "40px",
                letterSpacing: "-0.4375px",
                textAlign: "center",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              {" "}
              ABOUT THE APPRENTICESHIP
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1838b45faf7747dba68084c9987c035b"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "147px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "22px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              STUDY COMMITMENT
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
