/** @jsx jsx */
import { jsx } from "@emotion/react";

export default function MyComponent(props) {
  return (
    <>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "235px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F60dea6943db54b8d9973610990d1b97c"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "156px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "18px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Program condition1
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fed3ade599f984cb8823c1aece9ee1ec0"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "161px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "18px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Program condition 2
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2fd93a1b1cc044e2b8e06f48636bd653"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "161px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "18px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Program condition 3
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fbbf87d3d16ff48f08e3050742ec1fcd1"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "161px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "18px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Program condition 4
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "235px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F772a7a5751904c3d936414ac1d2b1f0a"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "156px",
              color: "rgba(28, 224, 130, 1)",
              fontSize: "18px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Program condition1
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c688246d09e48d7aaae1b99417dd53a"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "161px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "18px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Program condition 2
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9bc2a435af484b5aa4a19614bc6a9f00"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "161px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "18px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Program condition 3
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F322cbe54a83046088689db27a36fae12"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "161px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "18px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Program condition 4
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "235px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe77a86af0a534396bc7668f64a282e62"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "156px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "18px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Program condition1
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8f3ca554bd144bff823f8b2c18a4d077"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "161px",
              color: "rgba(28, 224, 130, 1)",
              fontSize: "18px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Program condition 2
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F793eaefc28844ac5b9ebbc3797204332"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "161px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "18px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Program condition 3
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fedc7e730cb414c0eb3218ec55f460157"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "161px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "18px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Program condition 4
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "235px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3daf960a31064e5bb3f6ecb4c10e89ae"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "156px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "18px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Program condition1
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F80c6fbbd41b144e0840214da12bac72f"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "161px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "18px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Program condition 2
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6a7e3f892bd34d0287de96cd9ca33ad3"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "161px",
                color: "rgba(28, 224, 130, 1)",
                fontSize: "18px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Program condition 3
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f8e609660664318a2070f5d49b6972e"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "161px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "18px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Program condition 4
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "235px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6c6febe512df4b6e831f9309dd244755"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "156px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "18px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Program condition1
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F61c32cf01a0742ff834b5ad2df25361a"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "161px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "18px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Program condition 2
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F1b629fe9239448d0899eb0ba53a588ce"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "161px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "18px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Program condition 3
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe385b1dc93fd4c079526bfba4995908d"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "161px",
                color: "rgba(28, 224, 130, 1)",
                fontSize: "18px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Program condition 4
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "375px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "812px",
          width: "375px",
          backgroundColor: "rgba(255, 255, 255, 1)",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "375px",
            boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.11999999731779099)",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "375px",
              height: "50px",
              width: "375px",
              backgroundColor: "rgba(104, 93, 197, 1)",
            }}
          />
          <div
            css={{
              display: "flex",
              maxWidth: "162px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "25px",
              width: "162px",
            }}
          >
            <div
              css={{
                display: "flex",
                flexDirection: "column",
                maxWidth: "153.94525146484375px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "153.94525146484375px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.181563377380371px",
                    width: "10.181563377380371px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb7497f4c33f43b4962a2c4bc4532811"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "133.03903853667003%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "11.855867385864258px",
                    width: "11.855867385864258px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2f43cf3d3f56483698e9b29999db85e6"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "114.25105885899829%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.045812606811523px",
                    width: "10.045812606811523px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fef836b8c89c24f07b0ab76e402d8a109"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "134.83681764165215%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.000553131103516px",
                    width: "10.000553131103516px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F06bdaff78d8c4105b8e2bdb85e0c9668"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "135.44704825515862%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.588821411132812px",
                    width: "10.588821411132812px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa9ed7572c6a94133a9ecac623034ecb5"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "133.07341389641024%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.226821899414062px",
                    width: "10.226821899414062px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fca69acb6215c4558b71733e251750e8d"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "135.11705024432095%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.045814514160156px",
                    width: "10.045814514160156px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd3bc17f5f7844e1ab2ec89132d072df1"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "134.83679204085894%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "58.55531311035156px",
                    width: "58.55531311035156px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Faf9ad93eebc34c7399d2abebef48a1c1"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "24.219525451722106%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "1.1765289306640625px",
                    width: "1.1765289306640625px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5bcf21c080ed449a8ca970018ff55d8a"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "100.44971143246222%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
          <div
            css={{
              maxWidth: "137px",
              color: "rgba(255, 255, 255, 1)",
              fontSize: "11px",
              letterSpacing: "0%",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            /INTERACTION Design
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "0px",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            flexDirection: "column",
            maxWidth: "35px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "35px",
              width: "35px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb7be949f848f404bb2e9c6900e339c0a"
                css={{
                  objectFit: "cover",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "85.71428571428571%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "286px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            height: "532px",
            width: "286px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "285.0137939453125px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "285.0137939453125px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "282.05517578125px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  height: "52px",
                  width: "282.05517578125px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    maxWidth: "31.558624267578125px",
                  }}
                >
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "31.558624267578125px",
                      height: "32px",
                      width: "31.558624267578125px",
                      borderColor: "rgba(218, 218, 218, 1)",
                      borderWidth: "1px",
                      borderStyle: "solid",
                    }}
                  />
                  <div
                    css={{
                      display: "flex",
                      position: "relative",
                      minWidth: "20px",
                      minHeight: "20px",
                      maxWidth: "9.704254150390625px",
                      width: "9.704254150390625px",
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4261eaa902f446ef87ce8a49c8050f03"
                        css={{
                          objectFit: "contain",
                          objectPosition: "center",
                          position: "absolute",
                          height: "100%",
                          width: "100%",
                          top: "0",
                          left: "0",
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: "100%",
                        paddingTop: "101.1515138888452%",
                        pointerEvents: "none",
                        fontSize: "0",
                      }}
                    />
                  </div>
                </div>
                <div
                  css={{
                    maxWidth: "220.91033935546875px",
                    color: "rgba(83, 83, 83, 1)",
                    fontSize: "18px",
                    lineHeight: "26px",
                    letterSpacing: "-0.27000001072883606px",
                    textAlign: "left",
                    fontFamily: "Mandali, sans-serif",
                  }}
                >
                  Do I get a job placement upon graduation?
                </div>
              </div>
              <div
                css={{
                  display: "flex",
                  flexGrow: "1",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "285.0137939453125px",
                  borderColor: "rgba(218, 218, 218, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0f47e97e34e449b881d861e44646cab1"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "0.7017204228310975%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "285.0137939453125px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "282.05517578125px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  height: "52px",
                  width: "282.05517578125px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    maxWidth: "31.558624267578125px",
                  }}
                >
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "31.558624267578125px",
                      height: "32px",
                      width: "31.558624267578125px",
                      borderColor: "rgba(218, 218, 218, 1)",
                      borderWidth: "1px",
                      borderStyle: "solid",
                    }}
                  />
                  <div
                    css={{
                      display: "flex",
                      position: "relative",
                      minWidth: "20px",
                      minHeight: "20px",
                      maxWidth: "9.704254150390625px",
                      width: "9.704254150390625px",
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa0aa18b4ff444533b3173dba1ca69a14"
                        css={{
                          objectFit: "contain",
                          objectPosition: "center",
                          position: "absolute",
                          height: "100%",
                          width: "100%",
                          top: "0",
                          left: "0",
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: "100%",
                        paddingTop: "101.1515138888452%",
                        pointerEvents: "none",
                        fontSize: "0",
                      }}
                    />
                  </div>
                </div>
                <div
                  css={{
                    maxWidth: "220.91033935546875px",
                    color: "rgba(83, 83, 83, 1)",
                    fontSize: "18px",
                    lineHeight: "26px",
                    letterSpacing: "-0.27000001072883606px",
                    textAlign: "left",
                    fontFamily: "Mandali, sans-serif",
                  }}
                >
                  What if I want to start my own company?{" "}
                </div>
              </div>
              <div
                css={{
                  display: "flex",
                  flexGrow: "1",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "285.0137939453125px",
                  borderColor: "rgba(218, 218, 218, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffccc20170fb14f64a77089ada858dc63"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "0.7017204228310975%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "285.0137939453125px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  flexGrow: "1",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "285.0137939453125px",
                  borderColor: "rgba(218, 218, 218, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F02ed50cfe46a4ab1afae1f4ea0c6e0a5"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "0.7017204228310975%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "282.05517578125px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  height: "32px",
                  width: "282.05517578125px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    maxWidth: "31.558624267578125px",
                  }}
                >
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "31.558624267578125px",
                      height: "32px",
                      width: "31.558624267578125px",
                      borderColor: "rgba(218, 218, 218, 1)",
                      borderWidth: "1px",
                      borderStyle: "solid",
                    }}
                  />
                  <div
                    css={{
                      display: "flex",
                      position: "relative",
                      minWidth: "20px",
                      minHeight: "20px",
                      maxWidth: "9.704254150390625px",
                      width: "9.704254150390625px",
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5aefb4feb6de4df788f580955ba3a38a"
                        css={{
                          objectFit: "contain",
                          objectPosition: "center",
                          position: "absolute",
                          height: "100%",
                          width: "100%",
                          top: "0",
                          left: "0",
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: "100%",
                        paddingTop: "101.1515138888452%",
                        pointerEvents: "none",
                        fontSize: "0",
                      }}
                    />
                  </div>
                </div>
                <div
                  css={{
                    maxWidth: "193.2965545654297px",
                    color: "rgba(83, 83, 83, 1)",
                    fontSize: "18px",
                    lineHeight: "26px",
                    letterSpacing: "-0.27000001072883606px",
                    textAlign: "left",
                    fontFamily: "Mandali, sans-serif",
                  }}
                >
                  What are my obligations?{" "}
                </div>
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "285.0137939453125px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  flexGrow: "1",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "285.0137939453125px",
                  borderColor: "rgba(218, 218, 218, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0014a34956694c7b960dc57d6f2560d5"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "0.7017204228310975%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "282.05517578125px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  height: "32px",
                  width: "282.05517578125px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    maxWidth: "31.558624267578125px",
                  }}
                >
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "31.558624267578125px",
                      height: "32px",
                      width: "31.558624267578125px",
                      borderColor: "rgba(218, 218, 218, 1)",
                      borderWidth: "1px",
                      borderStyle: "solid",
                    }}
                  />
                  <div
                    css={{
                      display: "flex",
                      position: "relative",
                      minWidth: "20px",
                      minHeight: "20px",
                      maxWidth: "9.704254150390625px",
                      width: "9.704254150390625px",
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2948568cccd44979b340455287545c61"
                        css={{
                          objectFit: "contain",
                          objectPosition: "center",
                          position: "absolute",
                          height: "100%",
                          width: "100%",
                          top: "0",
                          left: "0",
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: "100%",
                        paddingTop: "101.1515138888452%",
                        pointerEvents: "none",
                        fontSize: "0",
                      }}
                    />
                  </div>
                </div>
                <div
                  css={{
                    maxWidth: "204px",
                    color: "rgba(83, 83, 83, 1)",
                    fontSize: "18px",
                    lineHeight: "26px",
                    letterSpacing: "-0.27000001072883606px",
                    textAlign: "left",
                    fontFamily: "Mandali, sans-serif",
                  }}
                >
                  Do I need a visa?{" "}
                </div>
              </div>
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "284px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "90px",
              width: "284px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "284px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "284px",
                  height: "58px",
                  width: "284px",
                  borderRadius: "29px",
                  borderColor: "rgba(218, 218, 218, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              />
              <div
                css={{
                  display: "flex",
                  maxWidth: "235.51219177246094px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  height: "30px",
                  width: "235.51219177246094px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "30px",
                    justifyContent: "flex-start",
                    alignItems: "flex-start",
                    width: "30px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0ce9ed275a854d3c8e66fa03259887ae"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "98.95472208658855%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    maxWidth: "157.33798217773438px",
                    color: "rgba(104, 93, 197, 1)",
                    fontSize: "18px",
                    lineHeight: "24px",
                    letterSpacing: "-0.18000000715255737px",
                    textAlign: "left",
                    fontFamily: "Mandali, sans-serif",
                  }}
                >
                  Program Conditions
                </div>
              </div>
            </div>
            <div
              css={{
                maxWidth: "62.341461181640625px",
                color: "rgba(106, 106, 106, 1)",
                fontSize: "16px",
                lineHeight: "24px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Filter by:
            </div>
          </div>
          <div
            css={{
              maxWidth: "284.027587890625px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "35px",
              lineHeight: "40px",
              letterSpacing: "-0.4375px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            Frequently Asked Questions
          </div>
        </div>
      </div>
    </>
  );
}
