      // Figma Flutter Generator MobileWidget - COMPONENT
      Container(
      width: 375,
      height: 4769,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 62,
        left: 20,
        child: Container(
      width: 334,
      height: 172,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 91,
        left: -1.0151976346969604,
        child: Text('Interaction Design Apprenticeship', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(104, 93, 197, 1),
        fontFamily: 'Mandali',
        fontSize: 35,
        letterSpacing: -0.4375,
        fontWeight: FontWeight.normal,
        height: 1.1428571428571428
      ),)
      ),Positioned(
        top: 0.4117427170276642,
        left: 207.66233825683594,
        child: Transform.rotate(
        angle: -19.93770910298133 * (math.pi / 180),
        child: Container(
        width: 133.95314025878906,
        height: 133.6060333251953,
        decoration: BoxDecoration(
          image : DecorationImage(
          image: AssetImage('assets/images/Icon.png'),
          fit: BoxFit.fitWidth
      ),
  )
      ),
      )
      ),
        ]
      )
    )
      ),Positioned(
        top: 274,
        left: 19,
        child: Text('Powered by: Zeptolab', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(0, 0, 0, 1),
        fontFamily: 'Mandali',
        fontSize: 14,
        letterSpacing: -0.14000000059604645,
        fontWeight: FontWeight.normal,
        height: 1.7142857142857142
      ),)
      ),Positioned(
        top: 306,
        left: 19,
        child: Container(
        width: 62,
        height: 62,
        decoration: BoxDecoration(
          image : DecorationImage(
          image: AssetImage('assets/images/Logo.png'),
          fit: BoxFit.fitWidth
      ),
  )
      )
      ),Positioned(
        top: 392,
        left: 20,
        child: Container(
      width: 334,
      height: 274,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 114,
        left: 0,
        child: Container(
      width: 334,
      height: 160,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
        width: 334,
        height: 160,
        decoration: BoxDecoration(
          borderRadius : BorderRadius.only(
            topLeft: Radius.circular(4),
            topRight: Radius.circular(4),
            bottomLeft: Radius.circular(4),
            bottomRight: Radius.circular(4),
          ),
      color : Color.fromRGBO(255, 255, 255, 1),
      border : Border.all(
          color: Color.fromRGBO(218, 218, 218, 1),
          width: 1,
        ),
  )
      )
      ),Positioned(
        top: 24,
        left: 25,
        child: Container(
      width: 288,
      height: 112,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 68,
        left: 183,
        child: Text('Start date
3 Aug 2020', textAlign: TextAlign.left, style: TextStyle(
        color: undefined,
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),Positioned(
        top: 68,
        left: 0,
        child: Text('Application deadline
30 June 2020', textAlign: TextAlign.left, style: TextStyle(
        color: undefined,
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),Positioned(
        top: 0,
        left: 183,
        child: Text('Duration
1 Year Full-Time', textAlign: TextAlign.left, style: TextStyle(
        color: undefined,
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Text('Location
Bangkok', textAlign: TextAlign.left, style: TextStyle(
        color: undefined,
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 334,
      height: 98,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
        width: 334,
        height: 98,
        decoration: BoxDecoration(
          borderRadius : BorderRadius.only(
            topLeft: Radius.circular(4),
            topRight: Radius.circular(4),
            bottomLeft: Radius.circular(4),
            bottomRight: Radius.circular(4),
          ),
      color : Color.fromRGBO(255, 255, 255, 1),
      border : Border.all(
          color: Color.fromRGBO(218, 218, 218, 1),
          width: 1,
        ),
  )
      )
      ),Positioned(
        top: 24,
        left: 25,
        child: Container(
      width: 285,
      height: 50,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 26,
        left: 0,
        child: Text('6 Day  :  22 Hrs  :  56 Min  :  13 Seg ', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(83, 83, 83, 1),
        fontFamily: 'Mandali',
        fontSize: 20,
        letterSpacing: -0.20000000298023224,
        fontWeight: FontWeight.normal,
        height: 1.2
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Text('Application closes in
', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(104, 93, 197, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),Positioned(
        top: 722,
        left: 45,
        child: Container(
      width: 286,
      height: 598,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 544,
        left: 0,
        child: Container(
      width: 157.34375,
      height: 54,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
        width: 157.34375,
        height: 54,
        decoration: BoxDecoration(
          borderRadius : BorderRadius.only(
            topLeft: Radius.circular(27),
            topRight: Radius.circular(27),
            bottomLeft: Radius.circular(27),
            bottomRight: Radius.circular(27),
          ),
      color : Color.fromRGBO(104, 93, 197, 1),
  )
      )
      ),Positioned(
        top: 14,
        left: 38,
        child: Text('Apply now', textAlign: TextAlign.center, style: TextStyle(
        color: Color.fromRGBO(255, 255, 255, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.5
      ),)
      ),
        ]
      )
    )
      ),Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 286,
      height: 504,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 84,
        left: 0,
        child: Text('Harbour.Space has partnered with SCG to empower driven talent and eliminate the barriers to accessing exceptional education and career opportunities through a Masters Fellowship. 
Scholarship candidates will receive full financial support to complete their Masters program at Harbour.Space while gaining invaluable work experience through an internship with SCG, a leading company in the industry. ', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 18,
        letterSpacing: -0.27000001072883606,
        fontWeight: FontWeight.normal,
        height: 1.4444444444444444
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Text('A fully funded work-study program to launch your tech career ', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 18,
        letterSpacing: -0.27000001072883606,
        fontWeight: FontWeight.normal,
        height: 1.4444444444444444
      ),)
      ),Positioned(
        top: 478,
        left: 1,
        child: Text('Position: Marketing Performance', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 18,
        letterSpacing: -0.27000001072883606,
        fontWeight: FontWeight.normal,
        height: 1.4444444444444444
      ),)
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),Positioned(
        top: 1392,
        left: -1,
        child: Container(
      width: 376,
      height: 710,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 376,
      height: 710,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 167,
        left: 0,
        child: Container(
        width: 376,
        height: 401,
        decoration: BoxDecoration(
          color : Color.fromRGBO(104, 93, 197, 1),
  )
      )
      ),Positioned(
        top: 0,
        left: 21,
        child: SvgPicture.asset(
        'assets/images/pattern.svg',
        semanticsLabel: 'pattern'
      );
      ),Positioned(
        top: 155,
        left: 21,
        child: Container(
        width: 334,
        height: 555,
        decoration: BoxDecoration(
          borderRadius : BorderRadius.only(
            topLeft: Radius.circular(0),
            topRight: Radius.circular(0),
            bottomLeft: Radius.circular(4),
            bottomRight: Radius.circular(4),
          ),
      color : Color.fromRGBO(255, 255, 255, 1),
      border : Border.all(
          color: Color.fromRGBO(230, 230, 230, 1),
          width: 1,
        ),
  )
      )
      ),Positioned(
        top: 41,
        left: 62,
        child:  //Mask holder Template
    Container(
      width: 252,
      height: 252,
      child: null
    )
      ),
        ]
      )
    )
      ),Positioned(
        top: 334,
        left: 43,
        child: Container(
      width: 288,
      height: 322,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Text('About the apprenticeship', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(104, 93, 197, 1),
        fontFamily: 'Mandali',
        fontSize: 35,
        letterSpacing: -0.4375,
        fontWeight: FontWeight.normal,
        height: 1.1428571428571428
      ),)
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),Positioned(
        top: 1838,
        left: 45,
        child: Container(
      width: 285,
      height: 208,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Text('Our scholarships are designed to give talented and driven young people from any background access to top-class education, experience and network. We offer a fully-funded master’s degree alongside an apprenticeship and a guaranteed job upon graduation.  ', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 18,
        letterSpacing: -0.27000001072883606,
        fontWeight: FontWeight.normal,
        height: 1.4444444444444444
      ),)
      ),
        ]
      )
    )
      ),Positioned(
        top: 3096,
        left: 19,
        child: Container(
      width: 335,
      height: 215,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 335,
      height: 215,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
        width: 335,
        height: 215,
        decoration: BoxDecoration(
          borderRadius : BorderRadius.only(
            topLeft: Radius.circular(4),
            topRight: Radius.circular(4),
            bottomLeft: Radius.circular(4),
            bottomRight: Radius.circular(4),
          ),
      color : Color.fromRGBO(255, 255, 255, 1),
      border : Border.all(
          color: Color.fromRGBO(218, 218, 218, 1),
          width: 1,
        ),
  )
      )
      ),
        ]
      )
    )
      ),Positioned(
        top: 40,
        left: 25,
        child: Container(
      width: 288,
      height: 143,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 95,
        left: 0,
        child: Text('You’ll be guaranteed a 1 year contract with SCG upon graduation. ', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.5
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 168,
      height: 54,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 30,
        left: 0,
        child: Text('1 Year Full-Time', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 24,
        letterSpacing: -0.2181818187236786,
        fontWeight: FontWeight.normal,
        height: 1
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Text('A Full-Time Contract', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(104, 93, 197, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),
        ]
      )
    )
      ),Positioned(
        top: 86,
        left: 1.1368683772161603e-13,
        child: SvgPicture.asset(
        'assets/images/stroke.svg',
        semanticsLabel: 'stroke'
      );
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),Positioned(
        top: 3040,
        left: 20,
        child: Container(
      width: 334,
      height: 24,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 12,
        left: 247.05162048339844,
        child: SvgPicture.asset(
        'assets/images/stroke.svg',
        semanticsLabel: 'stroke'
      );
      ),Positioned(
        top: 0,
        left: 118,
        child: Text('GRADUATION', textAlign: TextAlign.center, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.145454540848732,
        fontWeight: FontWeight.normal,
        height: 1.5
      ),)
      ),Positioned(
        top: 12,
        left: 0,
        child: SvgPicture.asset(
        'assets/images/stroke.svg',
        semanticsLabel: 'stroke'
      );
      ),
        ]
      )
    )
      ),Positioned(
        top: 2721,
        left: 19,
        child: Container(
      width: 335,
      height: 287,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 335,
      height: 287,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
        width: 335,
        height: 287,
        decoration: BoxDecoration(
          borderRadius : BorderRadius.only(
            topLeft: Radius.circular(4),
            topRight: Radius.circular(4),
            bottomLeft: Radius.circular(4),
            bottomRight: Radius.circular(4),
          ),
      color : Color.fromRGBO(255, 255, 255, 1),
      border : Border.all(
          color: Color.fromRGBO(218, 218, 218, 1),
          width: 1,
        ),
  )
      )
      ),
        ]
      )
    )
      ),Positioned(
        top: 40,
        left: 25,
        child: Container(
      width: 288,
      height: 215,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 95,
        left: 0,
        child: Text('Immerse yourself in the professional world during your apprenticeship. You’ll learn the ropes from the best and get to apply your newly acquired knowledge in the field from day one.  ', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.5
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 204,
      height: 54,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 30,
        left: 0,
        child: Text('4 hours / day', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 24,
        letterSpacing: -0.2181818187236786,
        fontWeight: FontWeight.normal,
        height: 1
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Text('Apprenticeship Commitment', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(104, 93, 197, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),
        ]
      )
    )
      ),Positioned(
        top: 86,
        left: 1.1368683772161603e-13,
        child: SvgPicture.asset(
        'assets/images/stroke.svg',
        semanticsLabel: 'stroke'
      );
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),Positioned(
        top: 2426,
        left: 19,
        child: Container(
      width: 335,
      height: 263,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 335,
      height: 263,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
        width: 335,
        height: 263,
        decoration: BoxDecoration(
          borderRadius : BorderRadius.only(
            topLeft: Radius.circular(4),
            topRight: Radius.circular(4),
            bottomLeft: Radius.circular(4),
            bottomRight: Radius.circular(4),
          ),
      color : Color.fromRGBO(255, 255, 255, 1),
      border : Border.all(
          color: Color.fromRGBO(218, 218, 218, 1),
          width: 1,
        ),
  )
      )
      ),
        ]
      )
    )
      ),Positioned(
        top: 40,
        left: 25,
        child: Container(
      width: 288,
      height: 191,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 95,
        left: 0,
        child: Text('You will complete 15 modules to graduate. Daily classes are 3 hours, plus coursework to complete in your own time. ', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.5
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 136,
      height: 54,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 30,
        left: 0,
        child: Text('3 hours / day', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 24,
        letterSpacing: -0.2181818187236786,
        fontWeight: FontWeight.normal,
        height: 1
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Text('Study Commitment', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(104, 93, 197, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),
        ]
      )
    )
      ),Positioned(
        top: 86,
        left: 1.1368683772161603e-13,
        child: SvgPicture.asset(
        'assets/images/stroke.svg',
        semanticsLabel: 'stroke'
      );
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),Positioned(
        top: 2152,
        left: 45,
        child: Container(
      width: 285,
      height: 210,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 156,
        left: 0,
        child: Container(
      width: 285,
      height: 54,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 30,
        left: 0,
        child: Text('€8,400 (€700/month)', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 24,
        letterSpacing: -0.2181818187236786,
        fontWeight: FontWeight.normal,
        height: 1
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Text('Living Stipend', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(104, 93, 197, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),
        ]
      )
    )
      ),Positioned(
        top: 78,
        left: 0,
        child: Container(
      width: 108.81818389892578,
      height: 54,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 30,
        left: 0,
        child: Text('€22,900', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 24,
        letterSpacing: -0.2181818187236786,
        fontWeight: FontWeight.normal,
        height: 1
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Text('Tuition', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(104, 93, 197, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),
        ]
      )
    )
      ),Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 148.97727966308594,
      height: 54,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 30,
        left: 0,
        child: Text('€31,300', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 24,
        letterSpacing: -0.2181818187236786,
        fontWeight: FontWeight.normal,
        height: 1
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Text('Fellowship value', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(104, 93, 197, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),Positioned(
        top: 2230,
        left: 206,
        child: Container(
      width: 108.81818389892578,
      height: 54,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 30,
        left: 0,
        child: Text('€8,400', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(82, 82, 82, 1),
        fontFamily: 'Mandali',
        fontSize: 24,
        letterSpacing: -0.2181818187236786,
        fontWeight: FontWeight.normal,
        height: 1
      ),)
      ),Positioned(
        top: 0,
        left: 0,
        child: Text('Remaining', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(104, 93, 197, 1),
        fontFamily: 'Mandali',
        fontSize: 16,
        letterSpacing: -0.1599999964237213,
        fontWeight: FontWeight.normal,
        height: 1.375
      ),)
      ),
        ]
      )
    )
      ),Positioned(
        top: 3439,
        left: 0,
        child: Container(
      width: 375,
      height: 615,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 375,
      height: 257,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
        width: 375,
        height: 257,
        decoration: BoxDecoration(
          color : Color.fromRGBO(104, 93, 197, 1),
  )
      )
      ),Positioned(
        top: 0,
        left: 0,
        child: Container(
        width: 292,
        height: 257,
        decoration: BoxDecoration(
          border : Border.all(
          color: Color.fromRGBO(230, 230, 230, 1),
          width: 1,
        ),
      image : DecorationImage(
          image: AssetImage('assets/images/Pattern.png'),
          fit: BoxFit.fitWidth
      ),
  )
      )
      ),
        ]
      )
    )
      ),Positioned(
        top: 87,
        left: 19,
        child: null
      ),
        ]
      )
    )
      ),Positioned(
        top: 4124,
        left: 43,
        child: null
      ),Positioned(
        top: 31,
        left: 1,
        child: Container(
      width: 375,
      height: 50,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
        width: 375,
        height: 50,
        decoration: BoxDecoration(
          color : Color.fromRGBO(104, 93, 197, 1),
  )
      )
      ),Positioned(
        top: 13,
        left: 18,
        child: Container(
      width: 162,
      height: 25,
      decoration: BoxDecoration(
          color : Color.fromRGBO(255, 255, 255, 1),
  ),
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 4.727276802062988,
        left: 3.71061635017395,
        child: Container(
      width: 153.94525146484375,
      height: 14.454546928405762,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
      width: 153.94525146484375,
      height: 14.454546928405762,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0.318178653717041,
        left: 0,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0.318178653717041,
        left: 12.353629112243652,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0.318178653717041,
        left: 26.336313247680664,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0.318178653717041,
        left: 39.05195999145508,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0.045458316802978516,
        left: 51.40558624267578,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0.318178653717041,
        left: 64.84524536132812,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0.318178653717041,
        left: 78.37541198730469,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0,
        left: 95.38993835449219,
        child: Container(
      width: 58.55531311035156,
      height: 14.181818962097168,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0.318178653717041,
        left: 13.258675575256348,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0.318178653717041,
        left: 23.168724060058594,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0.045458316802978516,
        left: 36.78938293457031,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),Positioned(
        top: 0.318178653717041,
        left: 49.91229248046875,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),
        ]
      )
    )
      ),Positioned(
        top: 13.272727012634277,
        left: 91.7245864868164,
        child: SvgPicture.asset(
        'assets/images/vector.svg',
        semanticsLabel: 'vector'
      );
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),Positioned(
        top: 17,
        left: 186,
        child: Text('/INTERACTION Design', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(255, 255, 255, 1),
        fontFamily: 'Mandali',
        fontSize: 11,
        letterSpacing: 0 /*percentages not used in flutter. defaulting to zero*/,
        fontWeight: FontWeight.normal,
        height: 1
      ),)
      ),Positioned(
        top: 10,
        left: 322,
        child: Container(
      width: 35,
      height: 30,
      
      child: Stack(
        children: <Widget>[
          Positioned(
        top: 0,
        left: 0,
        child: Container(
        width: 35,
        height: 30,
        decoration: BoxDecoration(
          image : DecorationImage(
          image: AssetImage('assets/images/Screenshot20190811at841.png'),
          fit: BoxFit.fitWidth
      ),
  )
      )
      ),Positioned(
        top: 8,
        left: -41,
        child: Text('MENU', textAlign: TextAlign.left, style: TextStyle(
        color: Color.fromRGBO(255, 255, 255, 1),
        fontFamily: 'Mandali',
        fontSize: 14,
        letterSpacing: 0 /*percentages not used in flutter. defaulting to zero*/,
        fontWeight: FontWeight.normal,
        height: 1
      ),)
      ),
        ]
      )
    )
      ),
        ]
      )
    )
      ),
        ]
      )
    )
