/** @jsx jsx */
import { jsx } from "@emotion/react";

export default function MyComponent(props) {
  return (
    <div
      css={{
        display: "flex",
        maxWidth: "238px",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        height: "411px",
        width: "238px",
      }}
    >
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            position: "relative",
            minWidth: "20px",
            minHeight: "20px",
            maxWidth: "195px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            width: "195px",
          }}
        >
          <picture>
            <source
              srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16"
              type="image/webp"
            />

            <img
              src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16"
              srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F844638a51d814be58c40fd9facf58d16"
              css={{
                objectFit: "contain",
                objectPosition: "center",
                position: "absolute",
                height: "100%",
                width: "100%",
                top: "0",
                left: "0",
              }}
            />
          </picture>

          <div
            className="builder-image-sizer"
            css={{
              width: "100%",
              paddingTop: "15.384615384615385%",
              pointerEvents: "none",
              fontSize: "0",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
            height: "58px",
            width: "235px",
            borderRadius: "29px",
            borderColor: "rgba(230, 230, 230, 1)",
            borderWidth: "1px",
            borderStyle: "solid",
            backgroundColor: "rgba(255, 255, 255, 1)",
          }}
        />
        <div
          css={{
            maxWidth: "217px",
            color: "rgba(104, 93, 197, 1)",
            fontSize: "14px",
            lineHeight: "22px",
            letterSpacing: "-0.1599999964237213px",
            textAlign: "left",
            fontFamily: "Mandali, sans-serif",
          }}
        >
          APPRENTICESHIP COMMITMENT
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F95bf7fdb36a24bd680ce36853f9885c3"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "55px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "center",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            TWEETS
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2acd4290e51c4649a8bbf7e78dad1886"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "28px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            FSQ
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "235px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "235px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32cbe4035b1741a9aff5f292f62043e1"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "83px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "24px",
              letterSpacing: "-0.18000000715255737px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            HOME PAGE
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb5d59fec8a3d458db7f3f4de3e8acd3b"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "121px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "40px",
              letterSpacing: "-0.4375px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            PARTICIPATE NOW
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5c11b8df6af24744804ae9e0c7ba2598"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "193px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "40px",
                letterSpacing: "-0.4375px",
                textAlign: "center",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              {" "}
              ABOUT THE APPRENTICESHIP
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8844594c773c44b5b9b51f0081a01223"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "147px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "22px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              STUDY COMMITMENT
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
