/** @jsx jsx */
import { jsx } from "@emotion/react";

export default function MyComponent(props) {
  return (
    <>
      <div
        css={{
          display: "flex",
          maxWidth: "157.34375px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "54px",
          width: "157.34375px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "157.34375px",
            height: "54px",
            width: "157.34375px",
            borderRadius: "27px",
            backgroundColor: "rgba(241, 255, 219, 1)",
          }}
        />
        <div
          css={{
            maxWidth: "82px",
            color: "rgba(104, 93, 197, 1)",
            fontSize: "16px",
            lineHeight: "24px",
            letterSpacing: "-0.1599999964237213px",
            textAlign: "center",
            fontFamily: "Magra, sans-serif",
          }}
        >
          Apply now
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "375px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "812px",
          width: "375px",
          backgroundColor: "rgba(255, 255, 255, 1)",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "286px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "157.34375px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "54px",
              width: "157.34375px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "157.34375px",
                height: "54px",
                width: "157.34375px",
                borderRadius: "27px",
                backgroundColor: "rgba(104, 93, 197, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "82px",
                color: "rgba(255, 255, 255, 1)",
                fontSize: "16px",
                lineHeight: "24px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "center",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Apply now
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "286px",
            }}
          >
            <div
              css={{
                maxWidth: "285px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "18px",
                lineHeight: "26px",
                letterSpacing: "-0.27000001072883606px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Harbour.Space has partnered with SCG to empower driven talent and
              eliminate the barriers to accessing exceptional education and
              career opportunities through a Masters Fellowship. Scholarship
              candidates will receive full financial support to complete their
              Masters program at Harbour.Space while gaining invaluable work
              experience through an internship with SCG, a leading company in
              the industry.{" "}
            </div>
            <div
              css={{
                maxWidth: "285px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "18px",
                lineHeight: "26px",
                letterSpacing: "-0.27000001072883606px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              A fully funded work-study program to launch your tech career{" "}
            </div>
            <div
              css={{
                maxWidth: "285px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "18px",
                lineHeight: "26px",
                letterSpacing: "-0.27000001072883606px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Position: Marketing Performance
            </div>
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "375px",
            boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.11999999731779099)",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "375px",
              height: "50px",
              width: "375px",
              backgroundColor: "rgba(104, 93, 197, 1)",
            }}
          />
          <div
            css={{
              display: "flex",
              maxWidth: "162px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "25px",
              width: "162px",
            }}
          >
            <div
              css={{
                display: "flex",
                flexDirection: "column",
                maxWidth: "153.94525146484375px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "153.94525146484375px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.181563377380371px",
                    width: "10.181563377380371px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e4a39cebdfe49389088639c2b3dcfff"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "133.03903853667003%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "11.855867385864258px",
                    width: "11.855867385864258px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F564eb15d02654d9586879620a97f524d"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "114.25105885899829%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.045812606811523px",
                    width: "10.045812606811523px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd968c091b34c4a9c8aef4ee8742c8b60"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "134.83681764165215%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.000553131103516px",
                    width: "10.000553131103516px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51fc4cbcab4e45ec8c109a746df7a111"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "135.44704825515862%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.588821411132812px",
                    width: "10.588821411132812px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F023d4ec5daf44da4bdc02363654961e7"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "133.07341389641024%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.226821899414062px",
                    width: "10.226821899414062px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fde3c8279f51246c5a6f6339db16c3ec3"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "135.11705024432095%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.045814514160156px",
                    width: "10.045814514160156px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff081692754844424953a233b251a22c0"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "134.83679204085894%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "58.55531311035156px",
                    width: "58.55531311035156px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb3ebeaa6112843c6b7c6e7523cdbbb82"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "24.219525451722106%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "1.1765289306640625px",
                    width: "1.1765289306640625px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb56576aae4f64188a60b2c2968e953d3"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "100.44971143246222%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
          <div
            css={{
              maxWidth: "137px",
              color: "rgba(255, 255, 255, 1)",
              fontSize: "11px",
              letterSpacing: "0%",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            /INTERACTION Design
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "0px",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            flexDirection: "column",
            maxWidth: "35px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "35px",
              width: "35px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F300b5f37dd3f4a428792d79ac7694ffc"
                css={{
                  objectFit: "cover",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "85.71428571428571%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
        </div>
      </div>
    </>
  );
}
