/** @jsx jsx */
import { jsx } from "@emotion/react";

export default function MyComponent(props) {
  return (
    <>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "411px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F6d6b18f030e64ef6a3ff8cf046628acd"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "217px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "22px",
              letterSpacing: "-0.1599999964237213px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            APPRENTICESHIP COMMITMENT
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F16f905fac9c44011b2218b229ffcdee3"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "55px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "center",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              TWEETS
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe02eb058bff498fb57fe1aa3fbb7037"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "28px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              FSQ
            </div>
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            height: "235px",
            width: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76594f334acd4b959764114ce870fbd1"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "83px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              HOME PAGE
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "238px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf6f915176e34498b1da58b3b34197b8"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "121px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "40px",
                letterSpacing: "-0.4375px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              PARTICIPATE NOW
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe941c7759f5b4e7a9f982e994442eb91"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "193px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "40px",
                  letterSpacing: "-0.4375px",
                  textAlign: "center",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                {" "}
                ABOUT THE APPRENTICESHIP
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3cce7b1e229f4cc287455558d0cf9b7b"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "147px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "22px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                STUDY COMMITMENT
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "375px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "812px",
          width: "375px",
          backgroundColor: "rgba(255, 255, 255, 1)",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "375px",
            boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.11999999731779099)",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "375px",
              height: "50px",
              width: "375px",
              backgroundColor: "rgba(104, 93, 197, 1)",
            }}
          />
          <div
            css={{
              display: "flex",
              maxWidth: "162px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "25px",
              width: "162px",
            }}
          >
            <div
              css={{
                display: "flex",
                flexDirection: "column",
                maxWidth: "153.94525146484375px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "153.94525146484375px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.181563377380371px",
                    width: "10.181563377380371px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3adaf5417825429d853ae74ac0a3fc2d"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "133.03903853667003%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "11.855867385864258px",
                    width: "11.855867385864258px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76a89e7d95d74a05ac0f1e126db9f95e"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "114.25105885899829%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.045812606811523px",
                    width: "10.045812606811523px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F695a0d354ce74821852a38b0454311f4"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "134.83681764165215%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.000553131103516px",
                    width: "10.000553131103516px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fea396db520614e55b88a8bff475d3d12"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "135.44704825515862%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.588821411132812px",
                    width: "10.588821411132812px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd4475b1ee02f40549085bb8529dd45f4"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "133.07341389641024%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.226821899414062px",
                    width: "10.226821899414062px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb472080398c7446f8357a161885fe0e5"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "135.11705024432095%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.045814514160156px",
                    width: "10.045814514160156px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F320dd2f192814c79a9db19c2507f466e"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "134.83679204085894%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "58.55531311035156px",
                    width: "58.55531311035156px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffe34e2430fd64d7cac1d91daaed72de6"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "24.219525451722106%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "1.1765289306640625px",
                    width: "1.1765289306640625px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F68514bb08f5b4b1fa21e398101158593"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "100.44971143246222%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
          <div
            css={{
              maxWidth: "137px",
              color: "rgba(255, 255, 255, 1)",
              fontSize: "11px",
              letterSpacing: "0%",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            /INTERACTION Design
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "0px",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            flexDirection: "column",
            maxWidth: "35px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "35px",
              width: "35px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5353883c80294636a6553cc4c54bfbfc"
                css={{
                  objectFit: "cover",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "85.71428571428571%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "335px",
          }}
        >
          <div
            css={{
              display: "flex",
              flexDirection: "column",
              maxWidth: "335px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "335px",
                height: "263px",
                width: "335px",
                borderRadius: "4px",
                borderColor: "rgba(218, 218, 218, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "288px",
            }}
          >
            <div
              css={{
                maxWidth: "288px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "16px",
                lineHeight: "24px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              You will complete 15 modules to graduate. Daily classes are 3
              hours, plus coursework to complete in your own time.{" "}
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "136px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                height: "54px",
                width: "136px",
              }}
            >
              <div
                css={{
                  maxWidth: "137px",
                  color: "rgba(83, 83, 83, 1)",
                  fontSize: "24px",
                  lineHeight: "24px",
                  letterSpacing: "-0.2181818187236786px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                3 hours / day
              </div>
              <div
                css={{
                  maxWidth: "140px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "16px",
                  lineHeight: "22px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                Study Commitment
              </div>
            </div>
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "27.81617546081543px",
                width: "27.81617546081543px",
                borderColor: "rgba(218, 218, 218, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F5a45158b092845ca85d92fbb8cbffe47"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "3.5950305296596126%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "285px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "285px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "54px",
              width: "285px",
            }}
          >
            <div
              css={{
                maxWidth: "303.1363525390625px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "24px",
                lineHeight: "24px",
                letterSpacing: "-0.2181818187236786px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              €8,400 (€700/month)
            </div>
            <div
              css={{
                maxWidth: "126.95454406738281px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "16px",
                lineHeight: "22px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Living Stipend
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "108.81818389892578px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "54px",
              width: "108.81818389892578px",
            }}
          >
            <div
              css={{
                maxWidth: "117.88636779785156px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "24px",
                lineHeight: "24px",
                letterSpacing: "-0.2181818187236786px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              €22,900
            </div>
            <div
              css={{
                maxWidth: "62.181819915771484px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "16px",
                lineHeight: "22px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Tuition
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "148.97727966308594px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "54px",
              width: "148.97727966308594px",
            }}
          >
            <div
              css={{
                maxWidth: "111.40909576416016px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "24px",
                lineHeight: "24px",
                letterSpacing: "-0.2181818187236786px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              €31,300
            </div>
            <div
              css={{
                maxWidth: "147.68182373046875px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "16px",
                lineHeight: "22px",
                letterSpacing: "-0.1599999964237213px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Fellowship value
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "411px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8bb9478fdac14fe494475074e288ef32"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "217px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "22px",
              letterSpacing: "-0.1599999964237213px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            APPRENTICESHIP COMMITMENT
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2caf6c1e90c2421dbce5a1d9d4705dcd"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "55px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "center",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              TWEETS
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89ec730fbf4141acb3b25e97f4a9c39d"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "28px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              FSQ
            </div>
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            height: "235px",
            width: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F8dcea12805f14bf5b237beff7ffe9889"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "83px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              HOME PAGE
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "238px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3452cc2267934209958931d7008a4870"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "121px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "40px",
                letterSpacing: "-0.4375px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              PARTICIPATE NOW
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa8015801ebac48a8892d844e15fd8f37"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "193px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "40px",
                  letterSpacing: "-0.4375px",
                  textAlign: "center",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                {" "}
                ABOUT THE APPRENTICESHIP
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe0353296c47a4474ba2b70c6ad4c1f5f"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "147px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "22px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                STUDY COMMITMENT
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
