/** @jsx jsx */
import { jsx } from "@emotion/react";

export default function MyComponent(props) {
  return (
    <>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "411px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb55b2d722af47ccb26ccb94594181a2"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "217px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "22px",
              letterSpacing: "-0.1599999964237213px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            APPRENTICESHIP COMMITMENT
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fd60d45ef5348414d9800c1281a6543e7"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "55px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "center",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              TWEETS
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc61b33fbe11e42638dfb86a4a6ca8557"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "28px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              FSQ
            </div>
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            height: "235px",
            width: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F93aa09e531ca4d37a6872d9130a7da6b"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "83px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              HOME PAGE
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "238px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F49c3d2c60ffe4600b07b3e9b576fb66c"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "121px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "40px",
                letterSpacing: "-0.4375px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              PARTICIPATE NOW
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa4ed12433ba24bd49fe42efd10e91723"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "193px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "40px",
                  letterSpacing: "-0.4375px",
                  textAlign: "center",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                {" "}
                ABOUT THE APPRENTICESHIP
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fadd7ebba9bba4309b0d550f263616dbc"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "147px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "22px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                STUDY COMMITMENT
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "375px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "812px",
          width: "375px",
          backgroundColor: "rgba(255, 255, 255, 1)",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "375px",
            boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.11999999731779099)",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "375px",
              height: "50px",
              width: "375px",
              backgroundColor: "rgba(104, 93, 197, 1)",
            }}
          />
          <div
            css={{
              display: "flex",
              maxWidth: "162px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "25px",
              width: "162px",
            }}
          >
            <div
              css={{
                display: "flex",
                flexDirection: "column",
                maxWidth: "153.94525146484375px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "153.94525146484375px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.181563377380371px",
                    width: "10.181563377380371px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F89b0edce3a6a43d68e44458a5e811dae"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "133.03903853667003%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "11.855867385864258px",
                    width: "11.855867385864258px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F567373e10f2b42ae8282267cd407380e"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "114.25105885899829%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.045812606811523px",
                    width: "10.045812606811523px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Feb0ec112aa554e99b228db3b0e773106"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "134.83681764165215%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.000553131103516px",
                    width: "10.000553131103516px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F011073ed7db74131a11f4bbef712a77c"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "135.44704825515862%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.588821411132812px",
                    width: "10.588821411132812px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F097219b5ad11432d9a5c84667fbf1cd6"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "133.07341389641024%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.226821899414062px",
                    width: "10.226821899414062px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F7f504ec8a6ee4a949cb251a5c66d063e"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "135.11705024432095%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "10.045814514160156px",
                    width: "10.045814514160156px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fcf587cb7d0ca4ce1842e1aecf2805633"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "134.83679204085894%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "58.55531311035156px",
                    width: "58.55531311035156px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F78bde40fe43b440d9524f8aea3a4e388"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "24.219525451722106%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "1.1765289306640625px",
                    width: "1.1765289306640625px",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24e830e4a870447bbcf9b2707367ba71"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "100.44971143246222%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
          <div
            css={{
              maxWidth: "137px",
              color: "rgba(255, 255, 255, 1)",
              fontSize: "11px",
              letterSpacing: "0%",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            /INTERACTION Design
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "0px",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            flexDirection: "column",
            maxWidth: "35px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "35px",
              width: "35px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0896b0f7cf194a69b9d79e8456d3d7dc"
                css={{
                  objectFit: "cover",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "85.71428571428571%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "375px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "375px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "375px",
                height: "257px",
                width: "375px",
                backgroundColor: "rgba(104, 93, 197, 1)",
              }}
            />
            <div
              css={{
                display: "flex",
                flexGrow: "1",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "292px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F979c4cf31dbc4646978dde40b74c1911"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "88.01369863013699%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "335px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              height: "528px",
              width: "335px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "335px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "335px",
                  height: "456px",
                  width: "335px",
                  borderRadius: "4px",
                  borderColor: "rgba(218, 218, 218, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(251, 251, 251, 1)",
                }}
              />
              <div
                css={{
                  display: "flex",
                  maxWidth: "333.01776123046875px",
                  height: "108px",
                  width: "333.01776123046875px",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "310px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "104px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    maxWidth: "48px",
                  }}
                >
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "48px",
                      height: "48px",
                      width: "48px",
                      borderColor: "rgba(236, 236, 236, 1)",
                      borderWidth: "1px",
                      borderStyle: "solid",
                    }}
                  />
                  <div
                    css={{
                      display: "flex",
                      position: "relative",
                      minWidth: "20px",
                      minHeight: "20px",
                      maxWidth: "30px",
                      justifyContent: "flex-start",
                      alignItems: "flex-start",
                      width: "30px",
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F24b5ba67c6bb4c8eab84a13ba1031136"
                        css={{
                          objectFit: "contain",
                          objectPosition: "center",
                          position: "absolute",
                          height: "100%",
                          width: "100%",
                          top: "0",
                          left: "0",
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: "100%",
                        paddingTop: "100%",
                        pointerEvents: "none",
                        fontSize: "0",
                      }}
                    />
                  </div>
                </div>
                <div
                  css={{
                    display: "flex",
                    maxWidth: "48px",
                  }}
                >
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "48px",
                      height: "48px",
                      width: "48px",
                      borderColor: "rgba(236, 236, 236, 1)",
                      borderWidth: "1px",
                      borderStyle: "solid",
                    }}
                  />
                  <div
                    css={{
                      display: "flex",
                      position: "relative",
                      minWidth: "20px",
                      minHeight: "20px",
                      maxWidth: "30px",
                      justifyContent: "flex-start",
                      alignItems: "flex-start",
                      width: "30px",
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa01c5bcba8db41e3aa682c558d041f34"
                        css={{
                          objectFit: "contain",
                          objectPosition: "center",
                          position: "absolute",
                          height: "100%",
                          width: "100%",
                          top: "0",
                          left: "0",
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: "100%",
                        paddingTop: "100%",
                        pointerEvents: "none",
                        fontSize: "0",
                      }}
                    />
                  </div>
                </div>
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "287px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    maxWidth: "287px",
                    justifyContent: "flex-start",
                    alignItems: "flex-start",
                    height: "267px",
                    width: "287px",
                  }}
                >
                  <div
                    css={{
                      maxWidth: "229px",
                      color: "rgba(83, 83, 83, 1)",
                      fontSize: "16px",
                      lineHeight: "24px",
                      letterSpacing: "-0.1599999964237213px",
                      textAlign: "left",
                      fontFamily: "Mandali, sans-serif",
                    }}
                  >
                    Education · B.A. Visual Design
                  </div>
                  <div
                    css={{
                      maxWidth: "287px",
                      color: "rgba(83, 83, 83, 1)",
                      fontSize: "24px",
                      lineHeight: "29px",
                      letterSpacing: "-0.2181818187236786px",
                      textAlign: "left",
                      fontFamily: "Mandali, sans-serif",
                    }}
                  >
                    This Fellowship was a turning point in my career. I wouldn’t
                    be where I am today without the financial support and
                    experienced offered through the program.{" "}
                  </div>
                </div>
                <div
                  css={{
                    display: "flex",
                    maxWidth: "287px",
                  }}
                >
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "30px",
                      justifyContent: "flex-start",
                      alignItems: "flex-start",
                      height: "30px",
                      width: "30px",
                    }}
                  >
                    <div
                      css={{
                        display: "flex",
                        position: "relative",
                        minWidth: "20px",
                        minHeight: "20px",
                        maxWidth: "18px",
                        width: "18px",
                        opacity: "0.3",
                      }}
                    >
                      <picture>
                        <source
                          srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4"
                          type="image/webp"
                        />

                        <img
                          src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4"
                          srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F11133644941c4cbd9cece093d6169ae4"
                          css={{
                            objectFit: "contain",
                            objectPosition: "center",
                            position: "absolute",
                            height: "100%",
                            width: "100%",
                            top: "0",
                            left: "0",
                          }}
                        />
                      </picture>

                      <div
                        className="builder-image-sizer"
                        css={{
                          width: "100%",
                          paddingTop: "97.29729758368599%",
                          pointerEvents: "none",
                          fontSize: "0",
                        }}
                      />
                    </div>
                  </div>
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "201px",
                    }}
                  >
                    <div
                      css={{
                        display: "flex",
                        maxWidth: "137px",
                        justifyContent: "flex-start",
                        alignItems: "flex-start",
                        height: "45px",
                        width: "137px",
                      }}
                    >
                      <div
                        css={{
                          maxWidth: "145px",
                          color: "rgba(83, 83, 83, 1)",
                          fontSize: "16px",
                          lineHeight: "24px",
                          letterSpacing: "-0.1599999964237213px",
                          textAlign: "left",
                          fontFamily: "Mandali, sans-serif",
                        }}
                      >
                        Research Lead, SCG
                      </div>
                      <div
                        css={{
                          maxWidth: "95px",
                          color: "rgba(104, 93, 197, 1)",
                          fontSize: "16px",
                          lineHeight: "22px",
                          letterSpacing: "-0.1599999964237213px",
                          textAlign: "left",
                          fontFamily: "Mandali, sans-serif",
                        }}
                      >
                        Irene Pereyra
                      </div>
                    </div>
                    <div
                      css={{
                        display: "flex",
                        maxWidth: "48px",
                      }}
                    >
                      <div
                        css={{
                          display: "flex",
                          maxWidth: "48px",
                          height: "48px",
                          width: "48px",
                          backgroundColor: "rgba(230, 230, 230, 1)",
                        }}
                      />
                      <div
                        css={{
                          display: "flex",
                          maxWidth: "48px",
                          height: "48px",
                          width: "48px",
                          backgroundColor: "rgba(230, 230, 230, 1)",
                        }}
                      />
                      <div
                        css={{
                          display: "flex",
                          position: "relative",
                          minWidth: "20px",
                          minHeight: "20px",
                          maxWidth: "162px",
                          width: "162px",
                        }}
                      >
                        <picture>
                          <source
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f"
                            type="image/webp"
                          />

                          <img
                            src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F174008afde7747c59dcf6c83e072ad8f"
                            css={{
                              objectFit: "contain",
                              objectPosition: "center",
                              position: "absolute",
                              height: "100%",
                              width: "100%",
                              top: "0",
                              left: "0",
                            }}
                          />
                        </picture>

                        <div
                          className="builder-image-sizer"
                          css={{
                            width: "100%",
                            paddingTop: "55.55555555555556%",
                            pointerEvents: "none",
                            fontSize: "0",
                          }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "335px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "528px",
          width: "335px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "335px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "335px",
              height: "456px",
              width: "335px",
              borderRadius: "4px",
              borderColor: "rgba(218, 218, 218, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(251, 251, 251, 1)",
            }}
          />
          <div
            css={{
              display: "flex",
              maxWidth: "333.01776123046875px",
              height: "108px",
              width: "333.01776123046875px",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "310px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "104px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "48px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "48px",
                  height: "48px",
                  width: "48px",
                  borderColor: "rgba(236, 236, 236, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              />
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "30px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "30px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffc57d95ea69349a289329d03535d235d"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "100%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "48px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "48px",
                  height: "48px",
                  width: "48px",
                  borderColor: "rgba(236, 236, 236, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              />
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "30px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "30px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb4cadf3150e4208ae4b06cb7c6eb8a9"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "100%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "287px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "287px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                height: "267px",
                width: "287px",
                color: "rgba(83, 83, 83, 1)",
                fontSize: "24px",
                lineHeight: "29px",
                letterSpacing: "-0.2181818187236786px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              Harbour.Space was a great experience, an intense year and full of
              new knowledge, hard work, short nights but also friends and
              tremendous fun and learning.{" "}
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "287px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "30px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  height: "30px",
                  width: "30px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "18px",
                    width: "18px",
                    opacity: "0.3",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F51ce3999fd3d458da82ed2297c6dfd7b"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "97.29729758368599%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "201px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    maxWidth: "137px",
                    justifyContent: "flex-start",
                    alignItems: "flex-start",
                    height: "45px",
                    width: "137px",
                  }}
                >
                  <div
                    css={{
                      maxWidth: "200px",
                      color: "rgba(83, 83, 83, 1)",
                      fontSize: "16px",
                      lineHeight: "24px",
                      letterSpacing: "-0.1599999964237213px",
                      textAlign: "left",
                      fontFamily: "Mandali, sans-serif",
                    }}
                  >
                    Master in Interaction Design
                  </div>
                  <div
                    css={{
                      maxWidth: "99px",
                      color: "rgba(104, 93, 197, 1)",
                      fontSize: "16px",
                      lineHeight: "22px",
                      letterSpacing: "-0.1599999964237213px",
                      textAlign: "left",
                      fontFamily: "Mandali, sans-serif",
                    }}
                  >
                    Anna Egorova
                  </div>
                </div>
                <div
                  css={{
                    display: "flex",
                    maxWidth: "48px",
                  }}
                >
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "48px",
                      height: "48px",
                      width: "48px",
                      backgroundColor: "rgba(230, 230, 230, 1)",
                    }}
                  />
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "48px",
                      height: "48px",
                      width: "48px",
                      backgroundColor: "rgba(230, 230, 230, 1)",
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "335px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "528px",
          width: "335px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "335px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "335px",
              height: "456px",
              width: "335px",
              borderRadius: "4px",
              borderColor: "rgba(218, 218, 218, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(251, 251, 251, 1)",
            }}
          />
          <div
            css={{
              display: "flex",
              maxWidth: "333.01776123046875px",
              height: "108px",
              width: "333.01776123046875px",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "310px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "104px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "48px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "48px",
                  height: "48px",
                  width: "48px",
                  borderColor: "rgba(236, 236, 236, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              />
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "30px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "30px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F051b910e548c4fac8eeac6878b35fed7"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "100%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "48px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "48px",
                  height: "48px",
                  width: "48px",
                  borderColor: "rgba(236, 236, 236, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              />
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "30px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "30px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa74e4d94cc424a54aee655048e61fe61"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "100%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "287px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "287px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                height: "267px",
                width: "287px",
              }}
            >
              <div
                css={{
                  maxWidth: "0px",
                  color: "rgba(83, 83, 83, 1)",
                  fontSize: "16px",
                  lineHeight: "24px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                <div _text="" />
              </div>
              <div
                css={{
                  maxWidth: "287px",
                  color: "rgba(83, 83, 83, 1)",
                  fontSize: "24px",
                  lineHeight: "29px",
                  letterSpacing: "-0.2181818187236786px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                Without exaggeration, this year in Harbour.Space was a beautiful
                journey worth taking. I was surrounded by smart, unique and
                inspiring people throughout the whole year.
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "287px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "30px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  height: "30px",
                  width: "30px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "18px",
                    width: "18px",
                    opacity: "0.3",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F9f5652c74eac42b7bec1cbfe5a917f93"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "97.29729758368599%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "201px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    maxWidth: "137px",
                    justifyContent: "flex-start",
                    alignItems: "flex-start",
                    height: "45px",
                    width: "137px",
                  }}
                >
                  <div
                    css={{
                      maxWidth: "265px",
                      color: "rgba(83, 83, 83, 1)",
                      fontSize: "16px",
                      lineHeight: "24px",
                      letterSpacing: "-0.1599999964237213px",
                      textAlign: "left",
                      fontFamily: "Mandali, sans-serif",
                    }}
                  >
                    Master in High-tech Entrepreneurship
                  </div>
                  <div
                    css={{
                      maxWidth: "150px",
                      color: "rgba(104, 93, 197, 1)",
                      fontSize: "16px",
                      lineHeight: "22px",
                      letterSpacing: "-0.1599999964237213px",
                      textAlign: "left",
                      fontFamily: "Mandali, sans-serif",
                    }}
                  >
                    Anastasia Sarapulova
                  </div>
                </div>
                <div
                  css={{
                    display: "flex",
                    maxWidth: "48px",
                  }}
                >
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "48px",
                      height: "48px",
                      width: "48px",
                      backgroundColor: "rgba(200, 133, 133, 1)",
                    }}
                  />
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "48px",
                      height: "48px",
                      width: "48px",
                      backgroundColor: "rgba(200, 133, 133, 1)",
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "335px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "528px",
          width: "335px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "335px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "335px",
              height: "456px",
              width: "335px",
              borderRadius: "4px",
              borderColor: "rgba(218, 218, 218, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(251, 251, 251, 1)",
            }}
          />
          <div
            css={{
              display: "flex",
              maxWidth: "333.01776123046875px",
              height: "108px",
              width: "333.01776123046875px",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "310px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "104px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "48px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "48px",
                  height: "48px",
                  width: "48px",
                  borderColor: "rgba(236, 236, 236, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              />
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "30px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "30px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F4b4396acfeb0440caf843f0a962003c6"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "100%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "48px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "48px",
                  height: "48px",
                  width: "48px",
                  borderColor: "rgba(236, 236, 236, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                }}
              />
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "30px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "30px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0da6a117493c4607a17b6d8372246499"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "100%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "287px",
            }}
          >
            <div
              css={{
                display: "flex",
                maxWidth: "287px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                height: "267px",
                width: "287px",
              }}
            >
              <div
                css={{
                  maxWidth: "229px",
                  color: "rgba(83, 83, 83, 1)",
                  fontSize: "16px",
                  lineHeight: "24px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                Education · B.A. Visual Design
              </div>
              <div
                css={{
                  maxWidth: "287px",
                  color: "rgba(83, 83, 83, 1)",
                  fontSize: "24px",
                  lineHeight: "29px",
                  letterSpacing: "-0.2181818187236786px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                This Fellowship was a turning point in my career. I wouldn’t be
                where I am today without the financial support and experienced
                offered through the program.{" "}
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "287px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  maxWidth: "30px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  height: "30px",
                  width: "30px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    position: "relative",
                    minWidth: "20px",
                    minHeight: "20px",
                    maxWidth: "18px",
                    width: "18px",
                    opacity: "0.3",
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2dc4756764ca452a9229414a1c8dcced"
                      css={{
                        objectFit: "contain",
                        objectPosition: "center",
                        position: "absolute",
                        height: "100%",
                        width: "100%",
                        top: "0",
                        left: "0",
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: "100%",
                      paddingTop: "97.29729758368599%",
                      pointerEvents: "none",
                      fontSize: "0",
                    }}
                  />
                </div>
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "201px",
                }}
              >
                <div
                  css={{
                    display: "flex",
                    maxWidth: "137px",
                    justifyContent: "flex-start",
                    alignItems: "flex-start",
                    height: "45px",
                    width: "137px",
                  }}
                >
                  <div
                    css={{
                      maxWidth: "145px",
                      color: "rgba(83, 83, 83, 1)",
                      fontSize: "16px",
                      lineHeight: "24px",
                      letterSpacing: "-0.1599999964237213px",
                      textAlign: "left",
                      fontFamily: "Mandali, sans-serif",
                    }}
                  >
                    Research Lead, SCG
                  </div>
                  <div
                    css={{
                      maxWidth: "95px",
                      color: "rgba(104, 93, 197, 1)",
                      fontSize: "16px",
                      lineHeight: "22px",
                      letterSpacing: "-0.1599999964237213px",
                      textAlign: "left",
                      fontFamily: "Mandali, sans-serif",
                    }}
                  >
                    Irene Pereyra
                  </div>
                </div>
                <div
                  css={{
                    display: "flex",
                    maxWidth: "48px",
                  }}
                >
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "48px",
                      height: "48px",
                      width: "48px",
                      backgroundColor: "rgba(230, 230, 230, 1)",
                    }}
                  />
                  <div
                    css={{
                      display: "flex",
                      maxWidth: "48px",
                      height: "48px",
                      width: "48px",
                      backgroundColor: "rgba(230, 230, 230, 1)",
                    }}
                  />
                  <div
                    css={{
                      display: "flex",
                      position: "relative",
                      minWidth: "20px",
                      minHeight: "20px",
                      maxWidth: "162px",
                      width: "162px",
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F86f0463018dc424d9b028fe165b31c02"
                        css={{
                          objectFit: "contain",
                          objectPosition: "center",
                          position: "absolute",
                          height: "100%",
                          width: "100%",
                          top: "0",
                          left: "0",
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: "100%",
                        paddingTop: "55.55555555555556%",
                        pointerEvents: "none",
                        fontSize: "0",
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        css={{
          display: "flex",
          maxWidth: "238px",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          height: "411px",
          width: "238px",
        }}
      >
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              position: "relative",
              minWidth: "20px",
              minHeight: "20px",
              maxWidth: "195px",
              justifyContent: "flex-start",
              alignItems: "flex-start",
              width: "195px",
            }}
          >
            <picture>
              <source
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753"
                type="image/webp"
              />

              <img
                src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F0d09486fdd924331968f03e35430f753"
                css={{
                  objectFit: "contain",
                  objectPosition: "center",
                  position: "absolute",
                  height: "100%",
                  width: "100%",
                  top: "0",
                  left: "0",
                }}
              />
            </picture>

            <div
              className="builder-image-sizer"
              css={{
                width: "100%",
                paddingTop: "15.384615384615385%",
                pointerEvents: "none",
                fontSize: "0",
              }}
            />
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
              height: "58px",
              width: "235px",
              borderRadius: "29px",
              borderColor: "rgba(230, 230, 230, 1)",
              borderWidth: "1px",
              borderStyle: "solid",
              backgroundColor: "rgba(255, 255, 255, 1)",
            }}
          />
          <div
            css={{
              maxWidth: "217px",
              color: "rgba(104, 93, 197, 1)",
              fontSize: "14px",
              lineHeight: "22px",
              letterSpacing: "-0.1599999964237213px",
              textAlign: "left",
              fontFamily: "Mandali, sans-serif",
            }}
          >
            APPRENTICESHIP COMMITMENT
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F99d66738334249eea659fada12b07f5d"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "55px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "center",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              TWEETS
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3b67ce7300154850b335ca4bac068555"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "28px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              FSQ
            </div>
          </div>
        </div>
        <div
          css={{
            display: "flex",
            maxWidth: "238px",
            justifyContent: "flex-start",
            alignItems: "flex-start",
            height: "235px",
            width: "238px",
          }}
        >
          <div
            css={{
              display: "flex",
              maxWidth: "235px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F2e04f40ccb384f268752d8f17819c1ba"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "83px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "24px",
                letterSpacing: "-0.18000000715255737px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              HOME PAGE
            </div>
          </div>
          <div
            css={{
              display: "flex",
              maxWidth: "238px",
            }}
          >
            <div
              css={{
                display: "flex",
                position: "relative",
                minWidth: "20px",
                minHeight: "20px",
                maxWidth: "195px",
                justifyContent: "flex-start",
                alignItems: "flex-start",
                width: "195px",
              }}
            >
              <picture>
                <source
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc"
                  type="image/webp"
                />

                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff129b07b3cf5488981a6f7f91bb44fdc"
                  css={{
                    objectFit: "contain",
                    objectPosition: "center",
                    position: "absolute",
                    height: "100%",
                    width: "100%",
                    top: "0",
                    left: "0",
                  }}
                />
              </picture>

              <div
                className="builder-image-sizer"
                css={{
                  width: "100%",
                  paddingTop: "15.384615384615385%",
                  pointerEvents: "none",
                  fontSize: "0",
                }}
              />
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
                height: "58px",
                width: "235px",
                borderRadius: "29px",
                borderColor: "rgba(230, 230, 230, 1)",
                borderWidth: "1px",
                borderStyle: "solid",
                backgroundColor: "rgba(255, 255, 255, 1)",
              }}
            />
            <div
              css={{
                maxWidth: "121px",
                color: "rgba(104, 93, 197, 1)",
                fontSize: "14px",
                lineHeight: "40px",
                letterSpacing: "-0.4375px",
                textAlign: "left",
                fontFamily: "Mandali, sans-serif",
              }}
            >
              PARTICIPATE NOW
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ff95710c0546347cfabed4f3e3cbcf999"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "193px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "40px",
                  letterSpacing: "-0.4375px",
                  textAlign: "center",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                {" "}
                ABOUT THE APPRENTICESHIP
              </div>
            </div>
            <div
              css={{
                display: "flex",
                maxWidth: "235px",
              }}
            >
              <div
                css={{
                  display: "flex",
                  position: "relative",
                  minWidth: "20px",
                  minHeight: "20px",
                  maxWidth: "195px",
                  justifyContent: "flex-start",
                  alignItems: "flex-start",
                  width: "195px",
                }}
              >
                <picture>
                  <source
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17"
                    type="image/webp"
                  />

                  <img
                    src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc0f98754c0544473873fb315c70f2a17"
                    css={{
                      objectFit: "contain",
                      objectPosition: "center",
                      position: "absolute",
                      height: "100%",
                      width: "100%",
                      top: "0",
                      left: "0",
                    }}
                  />
                </picture>

                <div
                  className="builder-image-sizer"
                  css={{
                    width: "100%",
                    paddingTop: "15.384615384615385%",
                    pointerEvents: "none",
                    fontSize: "0",
                  }}
                />
              </div>
              <div
                css={{
                  display: "flex",
                  maxWidth: "235px",
                  height: "58px",
                  width: "235px",
                  borderRadius: "29px",
                  borderColor: "rgba(230, 230, 230, 1)",
                  borderWidth: "1px",
                  borderStyle: "solid",
                  backgroundColor: "rgba(255, 255, 255, 1)",
                }}
              />
              <div
                css={{
                  maxWidth: "147px",
                  color: "rgba(104, 93, 197, 1)",
                  fontSize: "14px",
                  lineHeight: "22px",
                  letterSpacing: "-0.1599999964237213px",
                  textAlign: "left",
                  fontFamily: "Mandali, sans-serif",
                }}
              >
                STUDY COMMITMENT
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
